name: Whizz
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0-113.0.dev <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter

  firebase_core: ^2.15.1
  json_annotation: ^4.8.0
  freezed_annotation: ^2.2.0
  firebase_auth: ^4.9.0
  shimmer: ^3.0.0
  cloud_firestore: ^4.9.1
  animated_snack_bar: ^0.3.1
  shared_preferences: ^2.2.1
  google_fonts: ^5.1.0
  lottie: ^2.6.0
  connectivity_plus: ^4.0.1
  internet_connection_checker: ^1.0.0+1
  percent_indicator: ^4.2.3
  salomon_bottom_bar: ^3.3.2
  animated_custom_dropdown: ^1.5.0
  intl: ^0.18.1
  google_maps_flutter: ^2.5.0
  super_tooltip: ^2.0.5
  pin_code_fields: ^7.4.0
  simple_tooltip: ^1.2.0
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.0.4
  geolocator: ^10.0.1
  flutter_svg: ^2.0.7

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

  freezed: ^2.3.2
  json_serializable: ^6.6.1
  build_runner: ^2.3.3

flutter: 
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/