// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDfgeu714rcHQimzB1ZlGztqepqDyAyCQ',
    appId: '1:658101380569:web:e2c79b3b69451a4d15e5c8',
    messagingSenderId: '658101380569',
    projectId: 'whizz-9e359',
    authDomain: 'whizz-9e359.firebaseapp.com',
    storageBucket: 'whizz-9e359.appspot.com',
    measurementId: 'G-QDYZ15PD5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ-p9icaGsA_k6rM-9yeWb59CLXqPBv-A',
    appId: '1:658101380569:android:8e8870c1d7db62ab15e5c8',
    messagingSenderId: '658101380569',
    projectId: 'whizz-9e359',
    storageBucket: 'whizz-9e359.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_Kbu6l_lYYk9aQjU1N6Uvb4F1yBXQdzI',
    appId: '1:658101380569:ios:d65e5d99f440ddd615e5c8',
    messagingSenderId: '658101380569',
    projectId: 'whizz-9e359',
    storageBucket: 'whizz-9e359.appspot.com',
    iosClientId: '658101380569-2vmo4tmltjh32q1rmmuq4mg7f4jal301.apps.googleusercontent.com',
    iosBundleId: 'com.example.whizz',
  );
}
