import 'dart:convert';
import 'dart:developer';
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:get/get.dart';

class ConstantData {
  // static Map<String, List<String>> stateMap = {
  //   "India": [
  //     'Andhra Pradesh',
  //     'Arunachal Pradesh',
  //     'Assam',
  //     'Bihar',
  //     'Chhattisgarh',
  //     'Goa',
  //     'Gujarat',
  //     'Haryana',
  //     'Himachal Pradesh',
  //     'Jharkhand',
  //     'Karnataka',
  //     'Kerala',
  //     'Madhya Pradesh',
  //     'Maharashtra',
  //     'Manipur',
  //     'Meghalaya',
  //     'Mizoram',
  //     'Nagaland',
  //     'Odisha',
  //     'Punjab',
  //     'Rajasthan',
  //     'Sikkim',
  //     'Tamil Nadu',
  //     'Telangana',
  //     'Tripura',
  //     'Uttar Pradesh',
  //     'Uttarakhand',
  //     'West Bengal',
  //     'Andaman and Nicobar Islands',
  //     'Chandigarh',
  //     'Dadra and Nagar Haveli and Daman and Diu',
  //     'Lakshadweep',
  //     'Delhi',
  //     'Puducherry',
  //   ],
  //   "Saudi Arabia": [
  //     "Riyadh",
  //     "Makkah",
  //     "Madinah",
  //     "Eastern Province",
  //     "Asir",
  //     "Tabuk",
  //     "Hail",
  //     "Northern Borders",
  //     "Jazan",
  //     "Najran",
  //     "Al-Bahah",
  //     "Al-Jawf"
  //   ],
  //   "Singapore": [
  //     'Central Region',
  //     'East Region',
  //     'North Region',
  //     'North-East Region',
  //     'West Region'
  //   ],
  //   "South Africa": [
  //     "Eastern Cape",
  //     "Free State",
  //     "Gauteng",
  //     "KwaZulu-Natal",
  //     "Limpopo",
  //     "Mpumalanga",
  //     "North West",
  //     "Northern Cape",
  //     "Western Cape",
  //   ],
  //   "Spain": [
  //     'Andalusia',
  //     'Aragon',
  //     'Asturias',
  //     'Balearic Islands',
  //     'Basque Country',
  //     'Canary Islands',
  //     'Cantabria',
  //     'Castile and Leon',
  //     'Castile-La Mancha',
  //     'Catalonia',
  //     'Extremadura',
  //     'Galicia',
  //     'La Rioja',
  //     'Madrid',
  //     'Murcia',
  //     'Navarre',
  //     'Valencian Community'
  //   ],
  //   "Sri Lanka": [
  //     'Western Province',
  //     'Central Province',
  //     'Southern Province',
  //     'Northern Province',
  //     'Eastern Province',
  //     'North Western Province',
  //     'North Central Province',
  //     'Uva Province',
  //     'Sabaragamuwa Province'
  //   ],
  //   "Switzerland": [
  //     "Aargau",
  //     "Appenzell Ausserrhoden",
  //     "Appenzell Innerrhoden",
  //     "Basel-Landschaft",
  //     "Basel-Stadt",
  //     "Bern",
  //     "Fribourg",
  //     "Geneva",
  //     "Glarus",
  //     "Graubünden",
  //     "Jura",
  //     "Lucerne",
  //     "Neuchâtel",
  //     "Nidwalden",
  //     "Obwalden",
  //     "Schaffhausen",
  //     "Schwyz",
  //     "Solothurn",
  //     "St. Gallen",
  //     "Thurgau",
  //     "Uri",
  //     "Valais",
  //     "Vaud",
  //     "Zug",
  //     "Zurich",
  //   ],
  //   "Thailand": [
  //     'Bangkok',
  //     'Krabi',
  //     'Phuket',
  //     'Chiang Mai',
  //     'Chiang Rai',
  //     'Phang Nga',
  //     'Surat Thani',
  //     'Nakhon Si Thammarat',
  //     'Phatthalung',
  //     'Songkhla',
  //     'Narathiwat',
  //     'Yala',
  //     'Pattani',
  //     'Trang',
  //     'Satun',
  //     'Ranong',
  //     'Phetchaburi',
  //     'Prachuap Khiri Khan',
  //     'Chumphon',
  //     'Surat Thani',
  //     'Nakhon Si Thammarat',
  //     'Phatthalung',
  //     'Songkhla',
  //     'Narathiwat',
  //     'Yala',
  //     'Pattani',
  //     'Trang',
  //     'Satun',
  //     'Ranong',
  //     'Phetchaburi',
  //     'Prachuap Khiri Khan',
  //     'Chumphon',
  //     'Nakhon Pathom',
  //     'Samut Sakhon',
  //     'Samut Songkhram',
  //     'Ratchaburi',
  //     'Phetchaburi',
  //     'Prachuap Khiri Khan',
  //     'Chumphon',
  //     'Nakhon Pathom',
  //     'Samut Sakhon',
  //     'Samut Songkhram',
  //     'Ratchaburi',
  //     'Kanchanaburi',
  //     'Suphan Buri',
  //     'Uthai Thani',
  //     'Chainat',
  //     'Sing Buri',
  //     'Lopburi',
  //     'Ang Thong',
  //     'Phra Nakhon Si Ayutthaya',
  //     'Saraburi',
  //     'Nakhon Nayok',
  //     'Prachinburi',
  //     'Chachoengsao',
  //     'Samut Prakan',
  //     'Nakhon Ratchasima',
  //     'Buri Ram',
  //     'Surin',
  //     'Sisaket',
  //     'Ubon Ratchathani',
  //     'Yasothon',
  //     'Amnat Charoen',
  //     'Mukdahan',
  //     'Nakhon Phanom',
  //     'Sakon Nakhon',
  //     'Nong Khai',
  //     'Bueng Kan',
  //     'Udon Thani',
  //     'Loei',
  //     'Nong Bua Lamphu',
  //     'Khon Kaen',
  //     'Maha Sarakham',
  //     'Roi Et',
  //     'Kalasin',
  //     'Sakon Nakhon',
  //     'Nong Khai',
  //     'Bueng Kan',
  //     'Udon Thani',
  //     'Loei',
  //     'Nong Bua Lamphu',
  //     'Khon Kaen',
  //     'Maha Sarakham',
  //     'Roi Et',
  //     'Kalasin',
  //     'Phayao',
  //     'Chiang Rai',
  //     'Mae Hong Son',
  //     'Nan',
  //     'Lampang',
  //     'Lamphun',
  //     'Uttaradit',
  //     'Phrae',
  //     'Nakhon Sawan',
  //     'Uthai Thani',
  //     'Chainat',
  //     'Sing Buri',
  //     'Lopburi',
  //     'Ang Thong',
  //     'Phra Nakhon Si Ayutthaya',
  //     'Saraburi',
  //     'Nakhon Nayok',
  //     'Prachinburi',
  //     'Chachoengsao',
  //     'Samut Prakan',
  //     'Chon Buri',
  //     'Rayong',
  //     'Chanthaburi',
  //     'Trat',
  //     'Chumphon',
  //     'Ranong',
  //     'Surat Thani',
  //     'Phang Nga',
  //     'Krabi',
  //     'Phuket',
  //     'Phang Nga',
  //     'Krabi',
  //     'Phuket',
  //     'Phatthalung',
  //     'Songkhla',
  //     'Narathiwat',
  //     'Yala',
  //     'Pattani',
  //     'Trang',
  //     'Satun'
  //   ],
  //   "Turkey": [
  //     "Adana",
  //     "Adıyaman",
  //     "Afyonkarahisar",
  //     "Ağrı",
  //     "Amasya",
  //     "Ankara",
  //     "Antalya",
  //     "Artvin",
  //     "Aydın",
  //     "Balıkesir",
  //     "Bilecik",
  //     "Bingöl",
  //     "Bitlis",
  //     "Bolu",
  //     "Burdur",
  //     "Bursa",
  //     "Çanakkale",
  //     "Çankırı",
  //     "Çorum",
  //     "Denizli",
  //     "Diyarbakır",
  //     "Edirne",
  //     "Elazığ",
  //     "Erzincan",
  //     "Erzurum",
  //     "Eskişehir",
  //     "Gaziantep",
  //     "Giresun",
  //     "Gümüşhane",
  //     "Hakkari",
  //     "Hatay",
  //     "Isparta",
  //     "Mersin",
  //     "İstanbul",
  //     "İzmir",
  //     "Kars",
  //     "Kastamonu",
  //     "Kayseri",
  //     "Kırklareli",
  //     "Kırşehir",
  //     "Kocaeli",
  //     "Konya",
  //     "Kütahya",
  //     "Malatya",
  //     "Manisa",
  //     "Kahramanmaraş",
  //     "Mardin",
  //     "Muğla",
  //     "Muş",
  //     "Nevşehir",
  //     "Niğde",
  //     "Ordu",
  //     "Rize",
  //     "Sakarya",
  //     "Samsun",
  //     "Siirt",
  //     "Sinop",
  //     "Sivas",
  //     "Tekirdağ",
  //     "Tokat",
  //     "Trabzon",
  //     "Tunceli",
  //     "Şanlıurfa",
  //     "Uşak",
  //     "Van",
  //     "Yozgat",
  //     "Zonguldak",
  //     "Aksaray",
  //     "Bayburt",
  //     "Karaman",
  //     "Kırıkkale",
  //     "Batman",
  //     "Şırnak",
  //     "Bartın",
  //     "Ardahan",
  //     "Iğdır",
  //     "Yalova",
  //     "Karabük",
  //     "Kilis",
  //     "Osmaniye",
  //     "Düzce"
  //   ],
  //   "Ukraine": [
  //     'Vinnytsia',
  //     'Volyn',
  //     'Dnipropetrovsk',
  //     'Donetsk',
  //     'Zhytomyr',
  //     'Zakarpattia',
  //     'Zaporizhzhia',
  //     'Ivano-Frankivsk',
  //     'Kyiv',
  //     'Kirovohrad',
  //     'Luhansk',
  //     'Lviv',
  //     'Mykolaiv',
  //     'Odesa',
  //     'Poltava',
  //     'Rivne',
  //     'Sumy',
  //     'Ternopil',
  //     'Kharkiv',
  //     'Kherson',
  //     'Khmelnytskyi',
  //     'Cherkasy',
  //     'Chernivtsi',
  //     'Chernihiv'
  //   ],
  //   "United Arab Emirates": [
  //     "Abu Dhabi",
  //     "Dubai",
  //     "Sharjah",
  //     "Ajman",
  //     "Umm Al-Quwain",
  //     "Ras Al Khaimah",
  //     "Fujairah",
  //   ],
  //   "United Kingdom": [
  //     'England',
  //     'Scotland',
  //     'Wales',
  //     'Northern Ireland',
  //   ],
  //   "United States of America": [
  //     'Alabama',
  //     'Alaska',
  //     'Arizona',
  //     'Arkansas',
  //     'California',
  //     'Colorado',
  //     'Connecticut',
  //     'Delaware',
  //     'Florida',
  //     'Georgia',
  //     'Hawaii',
  //     'Idaho',
  //     'Illinois',
  //     'Indiana',
  //     'Iowa',
  //     'Kansas',
  //     'Kentucky',
  //     'Louisiana',
  //     'Maine',
  //     'Maryland',
  //     'Massachusetts',
  //     'Michigan',
  //     'Minnesota',
  //     'Mississippi',
  //     'Missouri',
  //     'Montana',
  //     'Nebraska',
  //     'Nevada',
  //     'New Hampshire',
  //     'New Jersey',
  //     'New Mexico',
  //     'New York',
  //     'North Carolina',
  //     'North Dakota',
  //     'Ohio',
  //     'Oklahoma',
  //     'Oregon',
  //     'Pennsylvania',
  //     'Rhode Island',
  //     'South Carolina',
  //     'South Dakota',
  //     'Tennessee',
  //     'Texas',
  //     'Utah',
  //     'Vermont',
  //     'Virginia',
  //     'Washington',
  //     'West Virginia',
  //     'Wisconsin',
  //     'Wyoming'
  //   ],
  //   "Vietnam": [
  //     "Hanoi",
  //     "Ho Chi Minh City",
  //     "Hai Phong",
  //     "Da Nang",
  //     "Can Tho",
  //     "Quang Ninh",
  //     "Lao Cai",
  //     "Lam Dong",
  //     "Thua Thien Hue",
  //     "Khanh Hoa",
  //     "Binh Thuan",
  //     "Dong Nai",
  //     "Binh Duong",
  //     "Long An",
  //     "Tien Giang",
  //     "Vinh Long",
  //     "Ben Tre",
  //     "Tra Vinh",
  //     "Hau Giang",
  //     "An Giang",
  //     "Kien Giang",
  //     "Ca Mau",
  //     "Bac Ninh",
  //     "Bac Giang",
  //     "Phu Tho",
  //     "Vinh Phuc",
  //     "Hai Duong",
  //     "Hung Yen",
  //     "Nam Dinh",
  //     "Ninh Binh",
  //     "Thai Binh",
  //     "Ha Nam",
  //     "Quang Nam",
  //     "Quang Ngai",
  //     "Binh Dinh",
  //     "Phu Yen",
  //     "Kon Tum",
  //     "Gia Lai",
  //     "Dak Lak",
  //     "Dak Nong",
  //     "Lam Dong",
  //     "Binh Phuoc",
  //     "Tay Ninh",
  //     "Dong Thap",
  //     "An Giang",
  //     "Vinh Long",
  //     "Kien Giang",
  //     "Bac Lieu",
  //     "Soc Trang",
  //     "Hau Giang",
  //     "Cao Bang",
  //     "Bac Kan",
  //     "Lang Son",
  //     "Tuyen Quang",
  //     "Thai Nguyen",
  //     "Phu Tho",
  //     "Yen Bai",
  //     "Son La",
  //     "Hoa Binh",
  //     "Dien Bien",
  //     "Lai Chau",
  //     "Lao Cai",
  //     "Bac Ninh",
  //     "Bac Giang",
  //     "Ha Giang",
  //     "Quang Ninh",
  //     "Dien Bien",
  //     "Lai Chau",
  //     "Lao Cai",
  //     "Bac Ninh",
  //     "Bac Giang",
  //     "Ha Giang",
  //     "Quang Ninh",
  //     "Cao Bang",
  //     "Bac Kan",
  //     "Lang Son",
  //     "Tuyen Quang",
  //     "Thai Nguyen",
  //     "Phu Tho",
  //     "Yen Bai",
  //     "Son La",
  //     "Hoa Binh",
  //     "Dien Bien",
  //     "Lai Chau",
  //     "Lao Cai",
  //     "Bac Ninh",
  //     "Bac Giang",
  //     "Ha Giang",
  //     "Quang Ninh",
  //     "Dien Bien",
  //     "Lai Chau",
  //     "Lao Cai",
  //     "Bac Ninh",
  //     "Bac Giang",
  //     "Ha Giang",
  //     "Quang Ninh"
  //   ],
  //   "Yemen": [
  //     'Abyan',
  //     'Ad Dali',
  //     'Aden',
  //     'Al Bayda',
  //     'Al Hudaydah',
  //     'Al Jawf',
  //     'Al Mahrah',
  //     'Al Mahwit',
  //     'Amran',
  //     'Dhamar',
  //     'Hadhramaut',
  //     'Hajjah',
  //     'Ibb',
  //     'Lahij',
  //     'Marib',
  //     'Raymah',
  //     'Saada',
  //     'Sanaa',
  //     'Shabwah',
  //     'Socotra',
  //     'Taiz',
  //   ],
  //   "Zambia": [
  //     'Central',
  //     'Copperbelt',
  //     'Eastern',
  //     'Luapula',
  //     'Lusaka',
  //     'Muchinga',
  //     'Northern',
  //     'North-Western',
  //     'Southern',
  //     'Western',
  //   ],
  //   "Zimbabwe": [
  //     "Bulawayo",
  //     "Harare",
  //     "Manicaland",
  //     "Mashonaland Central",
  //     "Mashonaland East",
  //     "Mashonaland West",
  //     "Masvingo",
  //     "Matabeleland North",
  //     "Matabeleland South",
  //     "Midlands"
  //   ],
  // };
  static Map<String, List> stateMap = {};
  static Map<String, List> cityMap = {};
  List<String> countries = [];
  loadData(context) async {
    String data = await DefaultAssetBundle.of(context).loadString("assets/countries_data.json");
    List jsonResult = jsonDecode(data);
    for(var data in jsonResult){
      if(data['states'].isNotEmpty){
        countries.add(data['name']);
        stateMap[countries.last] = data['states'];
        for(var city in stateMap[countries.last]!){
          cityMap[city['name']] = city['cities'];
        }
      }
    }
    log('This is the state map: $stateMap');
    log('This is the city map: $cityMap');
  }

  /* Icons Asset */
  static const backArrow = 'assets/icons/back_icon.png';
  static const appSplash = 'assets/icons/whizz.gif';
  static const searchIcon = 'assets/icons/search_icon.png';
  static const loadingIcon = 'assets/icons/loading_icon.gif';
  static const appLogo = 'assets/images/app_logo.png';
  static const googleIcon = 'assets/images/google_icon.png';

}
